version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-dev'
before_build:
- cmd: dotnet restore
configuration: Release
artifacts:
- path: src\Core\bin\Release\*.nupkg
  name: NuGet
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
build:
  verbosity: normal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: PAO/O5vbA5FhGyMxquvwnFat6TwT9tLp0JkAC9xWZOYTae4SaldtKh93v4TVNKES
  on:
    branch: master