version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  verbosity: normal
after_build:
- ps: nuget pack Core.csproj -Version %appveyor_build_version%
test: off
artifacts:
- path: src\Core\bin\Release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: PAO/O5vbA5FhGyMxquvwnFat6TwT9tLp0JkAC9xWZOYTae4SaldtKh93v4TVNKES
  on:
    branch: master