version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  verbosity: normal
artifacts:
- path: src\Core\bin\release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: Ddx9R8TDSv9NPDUhGkQAE5lGqYtt/nZfjMG56q+n4AblRJQ/HPo8T41GEuGNjXJZ
  on:
    branch: master
- provider: NuGet
  server: https://ci.appveyor.com/nuget/sferguson82-ov95v3o0e59j
  api_key:
    secure: sUtJWVxeRcxUsY4dTnNV+XrJy9peSFxjs80cSgSy/ao=
  on:
    branch: stage