version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.0.{build}'
  package_version: '1.0.{build}'
  assembly_version: '1.0.{build}'
  file_version: '1.0.{build}'
  informational_version: '1.0.{build}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  verbosity: normal
test: off
artifacts:
- path: src\Core\bin\Release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: PAO/O5vbA5FhGyMxquvwnFat6TwT9tLp0JkAC9xWZOYTae4SaldtKh93v4TVNKES
  on:
    branch: master