using System;

namespace Core.Caching
{
    /// <summary>
    /// A method attribute to be used on methods that intend to cache their result and wish to rely on an application framework feature to execute the caching details
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class CacheAttribute : Attribute
    {
        /// <summary>
        /// The number of minutes to consider the cache entry generated by this method to be valid
        /// </summary>
        public double ExpirationTime { get; set; } = 120.0D;

        /// <summary>
        /// The ExpirationTime as a <see cref="TimeSpan"/>
        /// </summary>
        /// <returns>The ExpirationTime as a <see cref="TimeSpan"/></returns>
        public TimeSpan GetCacheDuration()
        {
            return TimeSpan.FromMinutes(ExpirationTime);
        }
    }
}
